[versions]

java = "21"

androidGradle = "8.12.3" # https://developer.android.com/reference/tools/gradle-api
androidCompileSDK = "36"
androidMinimalSDK = "28"

kmmio = "2.0.0"
karmaConventions = "1.8.2" # https://github.com/karmakrafts/karma-conventions/tags
kotlin = "2.2.21" # https://github.com/JetBrains/kotlin/releases
kotlinxIo = "0.8.2" # https://github.com/Kotlin/kotlinx-io/releases
dokka = "2.1.0" # https://github.com/Kotlin/dokka/releases
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases

[libraries]

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }

[plugins]

android-library = { id = "com.android.library", version.ref = "androidGradle" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }