[versions]
multiplatformMman = "1.3.0"
kotlin = "2.1.0"
kotlinxIo = "0.6.0" # https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-io-core
kotest = "5.9.1" # https://mvnrepository.com/artifact/io.kotest/kotest-assertions-core-jvm

dokka = "1.9.20" # https://github.com/Kotlin/dokka/releases

[libraries]
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
